name: Test all labs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-lab5:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies (lab5)
        run: cd lab5 && npm install
      - name: Compile TypeScript to JavaScript (lab5)
        run: cd lab5 && npm run build
      - name: Show compiled JavaScript (lab5)
        run: cd lab5 && cat dist/cat.js
      - name: Run the program (lab5)
        run: cd lab5 && node dist/cat.js
      - name: Test Lab5
        run: cd lab5 && npm test

  run-lab3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies (lab3)
        run: cd lab3 && npm install
      - name: Compile TypeScript to JavaScript (lab3)
        run: cd lab3 && npm run build
      - name: Show compiled JavaScript (lab3)
        run: cd lab3 && cat dist/math.js
      - name: Run Task 2 (lab3)
        run: cd lab3 && npm start

  test-lab4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies (lab4)
        run: cd lab4 && npm install
      - name: Compile TypeScript to JavaScript (lab4)
        run: cd lab4 && npm run build
      - name: Show compiled JavaScript (lab4)
        run: cd lab4 && cat dist/index.js
      - name: Run the program (lab4)
        run: cd lab4 && node dist/index.js
      - name: Test Lab4
        run: cd lab4 && npm test
